name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./alfredo-del-rayo-project

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./alfredo-del-rayo-project

    - name: Build the project
      run: npm run build

    - name: Upload Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: ./alfredo-del-rayo-project/dist
  
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Production Artifacts
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./alfredo-del-rayo-project/dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./alfredo-del-rayo-project/dist
  